services:
  umj_probe:
    restart: always
    build:
      context: .
      dockerfile: bcl_umj_probe/Dockerfile
    container_name: umjprobe
    environment:
      - PROBE_DB=127.0.0.1
      - PROBE_DB_PORT=6369
    network_mode: "host"
    cap_add:
      - NET_RAW
      - NET_ADMIN 
    depends_on:
      - umj_probe_redis
    volumes:
      - probe_app_data:/home/quart/probedata

  umj_probe_redis:
    image: redis:latest
    container_name: probedb
    command: ["redis-server", "--port", "6369", "--appendonly", "yes"]
    network_mode: "host"
    volumes:
      - probe_db_data:/data 
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6369", "PING"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  probe_app_data:
    external: true
  probe_db_data:
    external: true