services:
  umj_probe:
    restart: always
    build:
      context: .
      dockerfile: bcl_umj_probe/Dockerfile
    container_name: umjprobe
    environment:
      - PROBE_DB=127.0.0.1
      - PROBE_DB_PORT=6369
    network_mode: "host"
    cap_add:
      - NET_RAW
      - NET_ADMIN 
    depends_on:
      - umj_probe_redis
    volumes:
      - probe_app_data:/home/quart/probedata

  umj_probe_redis:
    image: redis:latest
    container_name: probedb
    command: ["redis-server", "--port", "6369", "--appendonly", "yes"]
    volumes:
      - probe_db_data:/data 

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - umj_probe

volumes:
  probe_app_data:
    external: true
  probe_db_data:
    external: true
  caddy_data:
    external: true
  caddy_config:
    external: true